# Generated by Django 4.0.8 on 2022-11-18 04:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import subscriptions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.CharField(max_length=30, validators=[subscriptions.models.Card.validate_card_num])),
                ('expire_date', models.DateField(validators=[subscriptions.models.Card.validate_expire_date])),
                ('card_holder_name', models.CharField(max_length=30)),
                ('cvc', models.CharField(max_length=30, validators=[subscriptions.models.Card.validate_cvc])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(unique=True)),
                ('subscription_type', models.CharField(choices=[('MONTHLY', 'charge by month'), ('ANNUALLY', 'charge annually')], default=None, max_length=50)),
                ('price', models.FloatField(default=0)),
                ('iteration', models.DurationField(default=datetime.timedelta(days=30), editable=False, verbose_name='iteration(days,hours,min,sec)')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('next_payment_date', models.DateField(blank=True, editable=False, null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_subscription', to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.CharField(editable=False, max_length=30)),
                ('date', models.DateField()),
                ('amount', models.FloatField(max_length=30)),
                ('recurrence_type', models.CharField(blank=True, choices=[('MONTHLY', 'charge by month'), ('ANNUALLY', 'charge annually')], max_length=10, null=True)),
                ('recurrence', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('UNPAID', 'unpaid'), ('SUCCESS', 'success'), ('CANCELLED', 'cancelled')], max_length=10)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
